# Generated by Django 5.0.1 on 2024-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.IntegerField()),
                ('edit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
