# Generated by Django 5.0.1 on 2024-01-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firm',
        ),
        migrations.DeleteModel(
            name='Org',
        ),
    ]
