# Generated by Django 5.0.1 on 2024-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='tested',
            field=models.BooleanField(default=False),
        ),
    ]
