# Generated by Django 5.0.1 on 2024-01-25 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_firm_tested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.BigIntegerField(verbose_name=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('firm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firm')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
