# Generated by Django 5.0.1 on 2024-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firm_id',
            new_name='firm',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
