# Generated by Django 5.0.1 on 2024-01-30 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_statusmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spec_fname', models.CharField(max_length=30)),
                ('spec_lname', models.CharField(blank=True, max_length=30, null=True)),
                ('spec_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('spec_color', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['spec_fname'],
            },
        ),
    ]
