# Generated by Django 5.0.1 on 2024-01-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_specmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaloonModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sln_name', models.CharField(max_length=50)),
                ('sln_address', models.CharField(blank=True, max_length=150, null=True)),
                ('sln_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('sln_note', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sln_name'],
            },
        ),
    ]
