# Generated by Django 5.0.1 on 2024-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_saloonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloonmodel',
            name='sln_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
