# Generated by Django 5.0.1 on 2024-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_saloonmodel_sln_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloonmodel',
            name='sln_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AddField(
            model_name='saloonmodel',
            name='sln_main',
            field=models.BooleanField(default=False),
        ),
    ]
