# Generated by Django 5.0.1 on 2024-02-15 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_saloonmodel_sln_color_saloonmodel_sln_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cl_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cl_saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saloonmodel')),
                ('cl_spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.specmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
