# Generated by Django 5.0.1 on 2024-02-19 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_calendar_calendarmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheduleModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_start', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=23), django.core.validators.MinValueValidator(limit_value=0)])),
                ('s_finish', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=23), django.core.validators.MinValueValidator(limit_value=0)])),
                ('d_dur', models.IntegerField()),
                ('cal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calendarmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
