# Generated by Django 5.0.1 on 2024-02-20 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_shedulemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mSheduleTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=40)),
                ('st_template', models.CharField(max_length=250)),
                ('st_note', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['st_name'],
            },
        ),
        migrations.DeleteModel(
            name='SheduleModel',
        ),
    ]
