# Generated by Django 5.0.1 on 2024-02-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_msheduletemplate_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='сl_shed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.msheduletemplate'),
        ),
    ]
