# Generated by Django 5.0.1 on 2024-02-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_calendarmodel_сl_shed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='сl_shed',
            new_name='cl_shed',
        ),
    ]
