# Generated by Django 5.0.1 on 2024-02-27 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_сl_shed_calendarmodel_cl_shed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mMeet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('m_dt', models.DateTimeField()),
                ('m_title', models.CharField(blank=True, max_length=30, null=True)),
                ('m_service', models.CharField(blank=True, max_length=250, null=True)),
                ('m_note', models.TextField(blank=True, null=True)),
                ('m_report', models.TextField(blank=True, null=True)),
                ('m_rating', models.IntegerField(default=0)),
                ('m_review', models.TextField(blank=True, null=True)),
                ('m_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('update', models.DateTimeField(auto_now=True)),
                ('m_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='app.client')),
                ('m_saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloon', to='app.saloonmodel')),
                ('m_spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec', to='app.specmodel')),
                ('m_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='app.statusmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['m_dt'],
            },
        ),
    ]
