# Generated by Django 5.0.1 on 2024-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_mmeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='specmodel',
            name='spec_active',
            field=models.BooleanField(default=True),
        ),
    ]
