# Generated by Django 5.0.1 on 2024-03-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_specmodel_spec_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='currency',
            field=models.CharField(choices=[('USD', '$ USD'), ('EUR', '€ EUR'), ('UAH', '₴ UAH')], default='UAH', max_length=3),
        ),
    ]
