# Generated by Django 5.0.1 on 2024-03-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_firm_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmeet',
            name='m_title',
        ),
        migrations.RemoveField(
            model_name='mmeet',
            name='m_value',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='bank',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='mmeet',
            name='m_status',
            field=models.IntegerField(choices=[(10, 'Reg'), (11, 'Done'), (12, 'Canc'), (13, 'Paid'), (20, 'Bot Reg'), (21, 'Bot Done'), (22, 'Bot Canc'), (23, 'Bot Paid'), (30, 'Api'), (31, 'Api Done'), (32, 'Api Canc'), (33, 'Api Paid')], default=10),
        ),
        migrations.CreateModel(
            name='mAgent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=40)),
                ('a_note', models.TextField(blank=True, null=True)),
                ('a_mail', models.EmailField(max_length=254)),
                ('a_phone', models.CharField(max_length=15)),
                ('a_person', models.CharField(max_length=100)),
                ('a_bank', models.CharField(blank=True, max_length=240, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_type', models.IntegerField(choices=[(1, 'Income'), (2, 'Outcome')], default=1)),
                ('d_num', models.CharField(blank=True, max_length=40, null=True)),
                ('d_date', models.DateTimeField()),
                ('d_name', models.CharField(max_length=40)),
                ('d_note', models.CharField(blank=True, max_length=150, null=True)),
                ('d_file', models.FileField(upload_to='uploads/')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.magent')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(1, 'Product'), (2, 'Material')], default=1)),
                ('p_code', models.CharField(blank=True, max_length=40, null=True)),
                ('p_name', models.CharField(max_length=40)),
                ('p_note', models.CharField(blank=True, max_length=250, null=True)),
                ('p_unit', models.CharField(choices=[('шт', 'Штука'), ('г', 'Грамм'), ('л', 'Літр'), ('м', 'Метр')], default='шт', max_length=3)),
                ('update', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'p_name'],
            },
        ),
        migrations.CreateModel(
            name='mDocdetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mdocument')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mproducts')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='mCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update', models.DateTimeField(auto_now=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mmeet')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mproducts')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
