# Generated by Django 5.0.1 on 2024-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_mmeet_m_title_remove_mmeet_m_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdocument',
            name='d_name',
        ),
        migrations.AlterField(
            model_name='mdocument',
            name='d_type',
            field=models.IntegerField(choices=[(1, 'Прибуткова накладна'), (20, 'Видаткова накладна')], default=1),
        ),
        migrations.AlterField(
            model_name='mproducts',
            name='category',
            field=models.IntegerField(choices=[(1, 'Товар'), (2, 'Матеріал')], default=1),
        ),
        migrations.AlterField(
            model_name='mproducts',
            name='p_unit',
            field=models.IntegerField(choices=[(1, 'шт'), (2, 'г'), (3, 'л'), (4, 'м')], default=1),
        ),
    ]
