# Generated by Django 5.0.1 on 2024-03-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_mdocument_d_name_alter_mdocument_d_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdocument',
            name='firm',
        ),
        migrations.AddField(
            model_name='mdocument',
            name='saloon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.saloonmodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StatusModel',
        ),
    ]
