# Generated by Django 5.0.1 on 2024-03-10 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_mdocument_firm_mdocument_saloon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n_query', models.CharField(blank=True, max_length=250, null=True)),
                ('n_value', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
