# Generated by Django 5.0.1 on 2024-03-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_specmodel_options_alter_specmodel_spec_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='066205', max_length=12),
            preserve_default=False,
        ),
    ]
