# Generated by Django 5.0.1 on 2024-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='magent',
            name='a_code',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
