# Generated by Django 5.0.1 on 2024-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_magent_a_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magent',
            name='a_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='magent',
            name='a_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magent',
            name='a_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
